name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Binary
        run: make
      - name: Simple Test
        run: |
          ./dummy-server.bin &
          sleep 3
          curl -s -k https://localhost:8443
          kill $!
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: ./dummy-server.bin

